/home/x/xty20/venv/lib/python3.8/site-packages/pytorch_lightning/utilities/seed.py:48: LightningDeprecationWarning: `pytorch_lightning.utilities.seed.seed_everything` has been deprecated in v1.8.0 and will be removed in v2.0.0. Please use `lightning_fabric.utilities.seed.seed_everything` instead.
  rank_zero_deprecation(
[rank: 0] Global seed set to 0
[rank: 0] Global seed set to 2
[nltk_data] Downloading package wordnet to /home/x/xty20/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/x/xty20/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/x/xty20/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/x/xty20/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /home/x/xty20/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     /home/x/xty20/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Traceback (most recent call last):
  File "/home/x/xty20/project/main3.py", line 30, in <module>
    better_text_classify()
  File "/gpfs/home/x/xty20/project/src/models/train_model.py", line 261, in better_text_classify
    steps_per_epoch = int(len(data.train_dataloader())),
  File "/gpfs/home/x/xty20/project/src/data/bias_detection_data.py", line 88, in train_dataloader
    return DataLoader(self.split_and_pad_data(self.train_dataset, augment = True), batch_size=self.batch_size, shuffle = True)
  File "/gpfs/home/x/xty20/project/src/data/bias_detection_data.py", line 61, in split_and_pad_data
    input_lines, labels = augmentor.augment_dataset(zipped_lines, has_label = True)
  File "/gpfs/home/x/xty20/project/src/models/data_augmentors.py", line 377, in augment_dataset
    augmented_sentences = self.generate_pairwise_and_augment(data_iter, has_label)
  File "/gpfs/home/x/xty20/project/src/models/data_augmentors.py", line 363, in generate_pairwise_and_augment
    label, sentences = data
ValueError: too many values to unpack (expected 2)
